### ISSUE TITLE
[Task] Create a route to get the answer to a question based on given context

### ISSUE THREAD

**Issue by apoorvsxna** [scholar-labs/scholar-backend#6]
## Description
- This route should take a question as well as some context as the request, and return the answer as the response.

## Route
- Endpoint: /answer

## Suggested Implementation
- You can use Google's [Gemini API](https://ai.google.dev/gemini-api). Install [this package](https://pypi.org/project/google-generativeai/)
- Sample code for question-answering -
```
import google.generativeai as genai
genai.configure(api_key) # Enter your API key here as a string

model = genai.GenerativeModel('gemini-1.5-flash')

context = "In physics, a state of matter is one of the distinct forms in which matter can exist. Four states of matter are observable in everyday life: solid, liquid, gas, and plasma."

question = "How many states of matter are there?"

prompt = f"The context provided is: {context}. The question is: {question}. What is the answer?"

response = model.generate_content(prompt)

print(response)
```
- Get your API key [here](https://[aistudio.google.com/app/apikey](https://aistudio.google.com/app/apikey)).

**Comment by PShivam02** [comment]
I will work on this

**Comment by apoorvsxna** [comment]
@PShivam02 Assigned.
